version: "3.1"
services:
  app_database_service:
    image: postgres:16
    volumes:
      - dane_bazy2:/var/lib/postgresql/data
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - spending-app-net
    env_file:
      - .env
  
  spending_app:
    build: ../
    image: spending_app_image
    networks:
      - spending-app-net
    ports:
      - 5000:5000
    depends_on:
      - app_database_service

networks:
  spending-app-net:

volumes:
  dane_bazy2: