version: "3.1"
services:
  test_database:
    image: postgres:16
    volumes:
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    ports:
      - 5444:5432
